### ISSUE TITLE
Add a license to the project?

### ISSUE THREAD

**Issue by hr-oss** [ekaktusz/elephant#1]
Howdy! Love this game. Was curious if you may add a license to this repo so others can use it as well.? That would make it so that others can use it without worries you might sue them😆

Here’s how to add a license: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you so much !! :)

**Comment by ekaktusz** [comment]
Hi! Thanks for the suggestion. I've added a license (MIT), so feel free to use the code in your project! :) Have a nice day.
